language: node_js
sudo: false
node_js:
- '4'
- '7'
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: OCRGkJ4DhmwEboxmy5GYXp9W0EV3MjuCWkV9HUsHMH06kIhG56TpKK1ebecprBW3MUlZO/UNdRCyKz8hNzGGeYDpdUg4UbBQT6jL365wE0p5u+6AZ111Dcu0NEJt0mchSEC54N8aaI4lv2w1FRuhggwfVqYE849vTIY1cRJDaHE=
  - secure: B3DSMqcK4FDj5nPlWFtXoYIazPXsZlrHR23aY1XaFqWtjJPZ/4gLBgxI1rx2PXXwYbbgYN93wpkVxeFJ2sF9wqpzXCFEZ9ewKhjF0h7zze/LPhIaW5RfrFlfMIvSeHJB5L1bsL2lHbpAHUSBoyN8GDkjnjAqKXISjXqy6EaRUKw=
notifications:
  irc:
    channels:
    - secure: fAl4fu/JFDyBB1RRVHNX0QcMhx/9CnGMNnPdkf47XkPBDI7Z5E9DYT651nsDUxANf6HQEiXrqVyl+cm3rphBOFBk6hlCEYpuFcCf6bYLOoBNDTqoIsU07JM6rOPRNjddrv8LYefS6Q04YmJk0ifyYLcYK8iWC52ZcEF0KIl+zVA=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: A2RXl34pn8/zgyrO4IuEFx8FhDYLXKT2UYjEaDowKq9+cmkGfx6f3ZAqvJoAyBM3tCYtGPKKDD5FtWxjp/XNDmVnvuKC5sYKk0n2mvde/SGzA8RvkLgxBa3vs7kOPncl5UORdizsjhwWp5FWrsmpcw5MB4WVarj6IiuZqZeDjVw=
  on:
    tags: true
    repo: taskcluster/fast-azure-storage
